name = "Minimal"
license = "Apache-2.0"
licenselink = "https://github.com/ChrisWilding/www.chriswilding.co.uk/blob/master/LICENSE"
description = "Minimal theme for Chris Wilding's personal website"
homepage = "https://www.chriswilding.co.uk/"
tags = []
features = []
min_version = "0.54"

[author]
  name = "Chris Wilding"
  homepage = "https://www.chriswilding.co.uk/"
